name: Build and Deploy to ECS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPO: ${{ vars.ECR_REPO }}

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Save results in artififact
        uses: actions/checkout@v3
      - run: docker build --compress -t proxy .
      - run: docker save --output image.tar proxy
      - uses: actions/upload-artifact@v3
        with:
          name: image
          path: image.tar
  
  push:
    name: ECR push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download image build from previus job
        uses: actions/download-artifact@v3
        with:
          name: image
      - shell: bash
        run: |
          docker load --input image.tar
